%BLOCKNUFFT3D - 
%
% Syntax:  [out, spread] = blocknufft3d(N1, N2, N3, xyz, d, eps, K1, K2, K3, num_threads)
%
% Inputs:
%    N1 - int
%    N2 - int
%    N3 - int
%    xyz - double (M,3)
%    d - complex double (M,1)
%    eps - double
%    K1 - int
%    K2 - int
%    K3 - int
%    num_threads - int
%
% Outputs:
%    out - complex double (N1,N2,N3)
%    spread - complex double (N1 * 2,N2 * 2,N3 * 2)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
